ReservationFinal/ReservationFinal.MVC.UI/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationFinal.DATA.EF;
using Microsoft.AspNet.Identity;

namespace ReservationFinal.MVC.UI.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private ReservationFinalEntities db = new ReservationFinalEntities();
        // GET: Reservations
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            var assets = db.OwnerInstruments.Where(i => i.OwnerID == currentUser && i.IsActive).Count();

            if (Request.IsAuthenticated && (User.IsInRole("Employee") || User.IsInRole("Admin"))) //If user is admin or employee, show all reservations
            {
                ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
                ViewBag.OwnerInstrumentID = new SelectList(db.OwnerInstruments, "OwnerInstrumentID", "InstrumentName");
                var reservations = db.Reservations.Include(r => r.Location).Include(r => r.OwnerInstrument);
               return View(reservations.ToList());
            }

            else if (assets != 0) //If user is not a Employee/Admin AND they have active assets, show only their reservations
            {
                ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
                ViewBag.OwnerInstrumentID = new SelectList(db.OwnerInstruments.Where(o => o.OwnerID == currentUser), "OwnerInstrumentID", "InstrumentName");
                var reservations = db.Reservations.Where(u => u.OwnerInstrument.OwnerID == currentUser);
                ViewBag.InstrumentsCount = db.OwnerInstruments.Where(i => i.IsActive && i.OwnerID == currentUser);
                return View(reservations.ToList());
            }

            else //The user has no active assets, send them to the Create Asset View.
            {
                return RedirectToAction("Create", "OwnerInstruments");
            }
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        #region AJAX Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AjaxCreate(Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                var location = db.Locations.AsNoTracking().Where(l => l.LocationID == reservation.LocationID).FirstOrDefault();

                if (location.Reservations.Where(r => r.ReservationDate == reservation.ReservationDate).ToList().Count >= location.ReservationLimit && !User.IsInRole("Admin"))
                {
                    throw new Exception();
                }
                else
                {
                    db.Reservations.Add(reservation);
                    db.SaveChanges();
                }
            }

            return Json(new {
            Location = reservation.LocationID,
            Instrument = reservation.OwnerInstrumentID,
            Date = reservation.ReservationDate
            });
        }
        #endregion
        // GET: Reservations/Create
        public ActionResult Create()
        {
            var currentUser = User.Identity.GetUserId();
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
            ViewBag.OwnerInstrumentID = new SelectList(db.OwnerInstruments.Where(o => o.OwnerID == currentUser), "OwnerInstrumentID", "InstrumentName");
            return View();
        }

        public ActionResult MaxCapacity()
        {
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationID,OwnerInstrumentID,LocationID,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                var location = db.Locations.Where(l => l.LocationID == reservation.LocationID).FirstOrDefault();

                if (location.Reservations.Where(r => r.ReservationDate == reservation.ReservationDate).ToList().Count >= location.ReservationLimit && !User.IsInRole("Admin"))
                {
                       return RedirectToAction("MaxCapacity");
                }

                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerInstrumentID = new SelectList(db.OwnerInstruments, "OwnerInstrumentID", "InstrumentName", reservation.OwnerInstrumentID);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            var currentUser = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerInstrumentID = new SelectList(db.OwnerInstruments.Where(model => model.OwnerID == currentUser), "OwnerInstrumentID", "InstrumentName", reservation.OwnerInstrumentID);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationID,OwnerInstrumentID,LocationID,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                var location = db.Locations.AsNoTracking().Where(l => l.LocationID == reservation.LocationID).FirstOrDefault();
                //Added AsNoTracking() to fix error

                if (location.Reservations.Where(r => r.ReservationDate == reservation.ReservationDate).ToList().Count >= location.ReservationLimit && !User.IsInRole("Admin"))
                {
                    return RedirectToAction("MaxCapacity");
                }
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", reservation.LocationID);
            ViewBag.OwnerInstrumentID = new SelectList(db.OwnerInstruments, "OwnerInstrumentID", "InstrumentName", reservation.OwnerInstrumentID);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReservationFinal/ReservationFinal.MVC.UI/Views/Reservations/Create.cshtml
@model ReservationFinal.DATA.EF.Reservation

@{
    ViewBag.Title = "Create new Reservation";
}

<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>

    @using (Html.BeginForm("Create", "Reservations", FormMethod.Post, new { @class = "bg-dark text-white rounded-3 p-2" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Reservation</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.OwnerInstrumentID, "Instrument", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OwnerInstrumentID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OwnerInstrumentID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LocationID, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
        </div>
    }
</div>

ReservationFinal/ReservationFinal.MVC.UI/Views/Reservations/Delete.cshtml
@model ReservationFinal.DATA.EF.Reservation

@{
    ViewBag.Title = "Delete Reservation";
}

<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>

    <h3 class="subHeader">Are you sure you want to delete this Reservation?</h3>
    <div class="bg-dark text-white rounded-3 p-2">
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReservationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Location.LocationName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Location.LocationName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OwnerInstrument.InstrumentName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OwnerInstrument.InstrumentName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
            </div>
        }
    </div>
</div>

ReservationFinal/ReservationFinal.MVC.UI/Views/Reservations/Details.cshtml
@model ReservationFinal.DATA.EF.Reservation

@{
    ViewBag.Title = "Reservation Details";
}

<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>

    <div class="bg-dark text-white rounded-3 p-2">
        <h4>Reservation</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReservationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Location.LocationName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Location.LocationName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OwnerInstrument.InstrumentName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OwnerInstrument.InstrumentName)
            </dd>

            <dt>
                Instrument Notes:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OwnerInstrument.SpecialNotes)
            </dd>

        </dl>

        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ReservationID }, new { @class = "text-white" }) |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
        </p>
    </div>
</div>

ReservationFinal/ReservationFinal.MVC.UI/Views/Reservations/Edit.cshtml
@model ReservationFinal.DATA.EF.Reservation

@{
    ViewBag.Title = "Edit Reservation";
}

<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>

    @using (Html.BeginForm("Edit", "Reservations", FormMethod.Post, new { @class = "bg-dark text-white p-2 rounded-3" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Reservation</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ReservationID)

            <div class="form-group">
                @Html.LabelFor(model => model.OwnerInstrumentID, "Instrument", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OwnerInstrumentID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OwnerInstrumentID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LocationID, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
        <div>
            @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
        </div>
    }
</div>

ReservationFinal/ReservationFinal.MVC.UI/Views/Reservations/Index.cshtml
@using Microsoft.AspNet.Identity;
@model IEnumerable<ReservationFinal.DATA.EF.Reservation>

@{
    ViewBag.Title = "Reservations";
    var currentUser = User.Identity.GetUserId();
}

<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>

    <div id="MessageContent"></div>

    <p>
        @*@Html.ActionLink("Create New", "Create")*@
        <button id="toggleReservationCreate" class="btn btn-primary">Create New</button>
        @*@Html.ActionLink("To Instruments", "Index", "OwnerInstruments", null, new { @class = "btn btn-dark"} )*@
    </p>

    @* Create a placeholder for the Partial View to render *@
    <div id="ReservationCreate">
        @Html.Partial("ReservationCreate", new ReservationFinal.DATA.EF.Reservation())
    </div>

    <div class="table-responsive-md">
        <table class="table table-striped reservationsTable" id="dataTable">
            <thead class="bg-dark text-white">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ReservationDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Location.LocationName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.OwnerInstrument.InstrumentName)
                    </th>
                    <th>
                        Notes:
                    </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="Reservation-@item.ReservationID">
                        <td>
                            @Html.DisplayFor(modelItem => item.ReservationDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Location.LocationName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OwnerInstrument.InstrumentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OwnerInstrument.SpecialNotes)
                        </td>
                        <td class="text-center">
                            @Html.ActionLink("Edit", "Edit", new { id = item.ReservationID }, new { @class = "btn btn-sm btn-dark" })
                            @Html.ActionLink("Details", "Details", new { id = item.ReservationID }, new { @class = "btn btn-sm btn-dark" })
                            @if (item.ReservationDate - DateTime.Now.Date <= TimeSpan.FromDays(7) && (User.IsInRole("Customer") || User.IsInRole("Employee")) && item.OwnerInstrument.OwnerID == currentUser)
                            {
                                @*@Html.ActionLink("Delete", "Delete", new { id = item.ReservationID }, new { @class = "btn btn-sm btn-dark", disabled = "true" })*@
                                <button class="btn btn-sm text-white deleteDisabled" title="You are unable to delete reservations within a week of the Reservation Date. Contact an admin if you really want to delete this reservation." data-toggle="tooltip" data-placement="top">Delete</button>
                            }
                            else if (User.IsInRole("Admin") || item.OwnerInstrument.OwnerID == currentUser)
                            {
                                @Html.ActionLink("Delete", "Delete", new { id = item.ReservationID }, new { @class = "btn btn-sm btn-dark" })
                            }

                            @if (User.IsInRole("Employee"))
                            {
                                @Html.ActionLink("Edit Notes", "Edit", "OwnerInstruments", new { id = item.OwnerInstrumentID }, new { @class = "btn btn-sm btn-dark", id = "editButton" })
                            }
                            else if (User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("Edit Instrument", "Edit", "OwnerInstruments", new { id = item.OwnerInstrumentID }, new { @class = "btn btn-sm btn-dark", id = "editButton" })
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/Scripts/DataTables.js")
    @Scripts.Render("~/Scripts/Ajax.js")
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                responsive: true,
                "language": {
                    "emptyTable": "You have no reservations. Be sure to <a class='text-dark' href='/OwnerInstruments/Create/'><b>add an instrument</b></a> first."
                }
            });
        });

        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>

    <!-- AJAX BELOW -->

    <script>
        //***************AJAX CREATE***************\\
        //Show the create form
        $('#ReservationCreate').hide(); //Start the page load with the create form hidden
        $('#toggleReservationCreate').click(function () {
            $('#ReservationCreate').toggle(); //Flip the create form between hidden and visible
        });

        $('#ReservationCreateForm').submit(function (e) {
            var formData = $(this).serializeArray(); // Capturing all of the inputs from the form and storing them in a JSON array
            console.log(formData);
            e.preventDefault();

            $.ajax({
                url: "/Reservations/AjaxCreate",
                type: "POST",
                data: formData,
                datatype: "json",
                error: function (e) {
                    $("#MessageContent").html("<div class = 'alert alert-danger'>Reservations full on that date at that location. Please try a different date or location.</div>")
                },
                success: function (s) {
                    $("#MessageContent").html("<div class = 'alert alert-success'>Successfully added Reservation. Refreshing...</div>");
                    // Reset the form
                    $("#ReservationCreateForm")[0].reset();
                    setInterval('location.reload()', 1000);
                    // Add the row with the code below
                    //$(function () {
                    //var row = "<tr>" + "<td>Refresh to View Options</td></tr>";
                    ////        "<td>" + s.LocationName + "</td>" +
                    ////        "<td>" + s.Address + "</td>" +
                    ////        "<td>" + s.City + "</td>" +
                    ////        "<td>" + s.State + "</td>" +
                    ////        "<td>" + s.ReservationLimit + "</td>" +
                    ////
                    //    $(".reservationsTable").append(row);
                    //}); unneeded because page is being automatically reloaded.
                    //$('#Reservation-' + data.ReservationID).replaceWith(row);
                }
            });
        });
    </script>
}

ReservationFinal/ReservationFinal.MVC.UI/Views/Reservations/MaxCapacity.cshtml
@{
    ViewBag.Title = "Sorry! Max Reservations";
}
<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>
    <div class="row">
        <div class="offset-md-3 col-md-6">
            <p>
                The location you are trying to reserve is already at max capacity on that day. Try to schedule for a different date.
            </p>
            <a class="text-center btn btn-dark" href="@Url.Action("Index", "Reservations")">Back to Reservations</a>
        </div>
    </div>
</div>

ReservationFinal/ReservationFinal.MVC.UI/Views/Reservations/ReservationCreate.cshtml
@model ReservationFinal.DATA.EF.Reservation

@using (Html.BeginForm("", "", FormMethod.Post, new { id = "ReservationCreateForm", @class = "bg-dark text-white p-2 rounded-3 mb-2" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create New Reservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OwnerInstrumentID, "Instrument", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerInstrumentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerInstrumentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}