ReservationFinal/ReservationFinal.MVC.UI/Controllers/OwnerInstrumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationFinal.DATA.EF;
using Microsoft.AspNet.Identity;
using System.Drawing; // Allows us to work with key functionality for image files
using ReservationFinal.MVC.UI.Utilities;

namespace ReservationFinal.MVC.UI.Controllers
{
    [Authorize]
    public class OwnerInstrumentsController : Controller
    {
        private ReservationFinalEntities db = new ReservationFinalEntities();

        // GET: OwnerInstruments
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            var ownerInstruments = db.OwnerInstruments.Where(o => o.OwnerID == currentUser).Include(o => o.InstrumentType).Include(o => o.UserDetail);
            if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Employee")))
            {
                ownerInstruments = db.OwnerInstruments.Where(o => o.IsActive).Include(o => o.InstrumentType).Include(o => o.UserDetail);
            }
            ViewBag.InstrumentsCount = db.OwnerInstruments.Where(i => i.IsActive && i.OwnerID == currentUser).Count();
            return View(ownerInstruments.ToList());
        }

        [Authorize(Roles = "Admin,Employee")]
        public ActionResult InactiveIndex()
        {
            var inactiveInstruments = db.OwnerInstruments.Where(o => !o.IsActive).Include(o => o.InstrumentType).Include(o => o.UserDetail);
            return View(inactiveInstruments.ToList());
        }
        // GET: OwnerInstruments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerInstrument ownerInstrument = db.OwnerInstruments.Find(id);
            if (ownerInstrument == null)
            {
                return HttpNotFound();
            }
            return View(ownerInstrument);
        }

        // GET: OwnerInstruments/Create
        public ActionResult Create()
        {
            var currentUser = User.Identity.GetUserId();
            ViewBag.InstrumentTypeID = new SelectList(db.InstrumentTypes, "InstrumentTypeID", "InstrumentTypeName");
            ViewBag.OwnerID = new SelectList(db.UserDetails, "UserID", "FirstName");
            ViewBag.InstrumentsCount = db.OwnerInstruments.Where(i => i.IsActive && i.OwnerID == currentUser).Count();
            return View();
        }

        // POST: OwnerInstruments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerInstrumentID,InstrumentName,OwnerID,InstrumentPhoto,SpecialNotes,IsActive,DateAdded,InstrumentTypeID")] OwnerInstrument ownerInstrument, HttpPostedFileBase instrumentPhoto)
        {
            var currentUser = User.Identity.GetUserId();
            bool isFirst = false;
            if (ModelState.IsValid)
            {
                #region File Upload
                string file = "NoImage.png";

                if (instrumentPhoto != null)
                {
                    file = instrumentPhoto.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (goodExts.Contains(ext.ToLower()) && instrumentPhoto.ContentLength <= 4194304)
                    {

                        // Create a new file name (using a GUID)
                        file = Guid.NewGuid() + ext;

                        #region Resize Image                        // This informs the program to save the image to this location in our file structure.
                        string savePath = Server.MapPath("~/Content/instImages/");

                        Image convertedImage = Image.FromStream(instrumentPhoto.InputStream);

                        int maxImageSize = 500;

                        int maxThumbSize = 100;

                        ImageServices.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                        #endregion
                    }
                }
                // No matter what, update the photoUrl with the value of the file variable
                ownerInstrument.InstrumentPhoto = file;
                #endregion
                if (db.OwnerInstruments.Where(i => i.OwnerID == currentUser).Count() == 0)
                {
                    isFirst = true;
                }
                db.OwnerInstruments.Add(ownerInstrument);
                db.SaveChanges();
            }

            ViewBag.InstrumentTypeID = new SelectList(db.InstrumentTypes, "InstrumentTypeID", "InstrumentTypeName", ownerInstrument.InstrumentTypeID);
            ViewBag.OwnerID = new SelectList(db.UserDetails, "UserID", "FirstName", ownerInstrument.OwnerID);

            if (isFirst)
            {
                return RedirectToAction("Create", "Reservations");
            }

            return RedirectToAction("Index");
        }
        // GET: OwnerInstruments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerInstrument ownerInstrument = db.OwnerInstruments.Find(id);
            if (ownerInstrument == null)
            {
                return HttpNotFound();
            }
            ViewBag.InstrumentTypeID = new SelectList(db.InstrumentTypes, "InstrumentTypeID", "InstrumentTypeName", ownerInstrument.InstrumentTypeID);
            ViewBag.OwnerID = new SelectList(db.UserDetails, "UserID", "FirstName", ownerInstrument.OwnerID);
            return View(ownerInstrument);
        }

        // POST: OwnerInstruments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OwnerInstrumentID,InstrumentName,OwnerID,InstrumentPhoto,SpecialNotes,IsActive,DateAdded,InstrumentTypeID")] OwnerInstrument ownerInstrument, HttpPostedFileBase instrumentPhoto)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                string file = "NoImage.png";

                if (instrumentPhoto != null)
                {
                    file = instrumentPhoto.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (goodExts.Contains(ext.ToLower()) && instrumentPhoto.ContentLength <= 4194304)
                    {

                        // Create a new file name (using a GUID)
                        file = Guid.NewGuid() + ext;

                        #region Resize Image                        // This informs the program to save the image to this location in our file structure.
                        string savePath = Server.MapPath("~/Content/instImages/");

                        Image convertedImage = Image.FromStream(instrumentPhoto.InputStream);

                        int maxImageSize = 500;

                        int maxThumbSize = 100;

                        ImageServices.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                        #endregion
                    }
                    ownerInstrument.InstrumentPhoto = file;
                }
                // No matter what, update the photoUrl with the value of the file variable
                
                #endregion
                db.Entry(ownerInstrument).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.InstrumentTypeID = new SelectList(db.InstrumentTypes, "InstrumentTypeID", "InstrumentTypeName", ownerInstrument.InstrumentTypeID);
            ViewBag.OwnerID = new SelectList(db.UserDetails, "UserID", "FirstName", ownerInstrument.OwnerID);
            return View(ownerInstrument);
        }

        // GET: OwnerInstruments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerInstrument ownerInstrument = db.OwnerInstruments.Find(id);
            if (ownerInstrument == null)
            {
                return HttpNotFound();
            }
            return View(ownerInstrument);
        }

        // POST: OwnerInstruments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OwnerInstrument ownerInstrument = db.OwnerInstruments.Find(id);
            if (ownerInstrument.IsActive)
            {
                ownerInstrument.IsActive = false;
            }
            else
            {
                ownerInstrument.IsActive = true;
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReservationFinal/ReservationFinal.MVC.UI/Views/OwnerInstruments/Create.cshtml
@using Microsoft.AspNet.Identity
@model ReservationFinal.DATA.EF.OwnerInstrument

@{
    ViewBag.Title = "Create New Instrument";
    var currentUser = User.Identity.GetUserId();
}
<h2 class="viewHeader">@ViewBag.Title</h2>
@if (ViewBag.InstrumentsCount == 0)
{
    <h3 class="text-center text-danger">You currently have no active instruments!</h3>
}
    <div class="container bg-dark text-white p-3 rounded-3">

        @using (Html.BeginForm("Create", "OwnerInstruments", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Instrument</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.DateAdded, new { @Value = DateTime.Now })
                @Html.HiddenFor(model => model.OwnerID, new { @Value = currentUser })
                @Html.HiddenFor(model => model.IsActive, new { @Value = true })
                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.InstrumentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InstrumentName, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.OwnerID, "OwnerID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("OwnerID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.OwnerID, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentTypeID, "Instrument Type", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("InstrumentTypeID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.InstrumentTypeID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="instrumentPhoto" />
                        @Html.ValidationMessageFor(model => model.InstrumentPhoto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>

            <div>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
            </div>
        }

    </div>

ReservationFinal/ReservationFinal.MVC.UI/Views/OwnerInstruments/Delete.cshtml
@model ReservationFinal.DATA.EF.OwnerInstrument

@{
    if (Model.IsActive)
    {
        ViewBag.Title = $"Deactivate {Model.InstrumentName}?";
    }
    else
    {
        ViewBag.Title = $"Reactivate {Model.InstrumentName}?";
    }
}

<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>
    <div class="bg-dark text-white rounded-3 p-2">
        <h4>Instrument</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.InstrumentName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.InstrumentName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.InstrumentPhoto)
            </dt>

            <dd>
                <img class="rounded-3" src="~/Content/instImages/t_@Model.InstrumentPhoto" alt="@Model.InstrumentName" title="@Model.InstrumentName" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SpecialNotes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SpecialNotes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateAdded)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateAdded)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.InstrumentType.InstrumentTypeName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.InstrumentType.InstrumentTypeName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserDetail.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserDetail.FirstName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-actions no-color">
        @if (Model.IsActive)
        {
            <input type="submit" value="Deactivate" class="btn btn-danger" /> @:|
        }
        else
        {
            <input type="submit" value="Reactivate" class="btn btn-success" /> @:|
        }
            @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
        </div>
        }
    </div>
</div>

ReservationFinal/ReservationFinal.MVC.UI/Views/OwnerInstruments/Details.cshtml
@model ReservationFinal.DATA.EF.OwnerInstrument

@{
    ViewBag.Title = $"{Model.InstrumentName} Details";
}

<div class="container" style="padding-top: 5%;">
    <div class="row align-items-center">
        <div class="col-md-5">
            <img class="instrumentPhoto" src="~/Content/instImages/@Model.InstrumentPhoto" />
        </div>
        <div class="col-md-4 bg-dark text-white rounded-3 p-2">
            <h4>@ViewBag.Title</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.InstrumentName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.InstrumentName)
                </dd>

                @*<dt>
                        @Html.DisplayNameFor(model => model.InstrumentPhoto)
                    </dt>*@

                @*<dd>
                        @Html.DisplayFor(model => model.InstrumentPhoto)
                    </dd>*@

                <dt>
                    @Html.DisplayNameFor(model => model.SpecialNotes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SpecialNotes)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateAdded)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateAdded)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.InstrumentType.InstrumentTypeName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.InstrumentType.InstrumentTypeName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UserDetail.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserDetail.FirstName)
                </dd>

            </dl>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.OwnerInstrumentID }, new { @class = "text-white" }) |
                @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
            </p>
        </div>
    </div>

</div>

ReservationFinal/ReservationFinal.MVC.UI/Views/OwnerInstruments/Edit.cshtml
@using Microsoft.AspNet.Identity;
@model ReservationFinal.DATA.EF.OwnerInstrument

@{
    ViewBag.Title = $"Edit {Model.InstrumentName}";
}

<div class="container">
    <h2 class="viewHeader">@ViewBag.Title</h2>
    @if (!User.IsInRole("Employee"))
    {
        using (Html.BeginForm("Edit", "OwnerInstruments", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "bg-dark text-white p-2 rounded-3" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Instrument</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.OwnerInstrumentID)
                @Html.HiddenFor(model => model.DateAdded)
                @Html.HiddenFor(model => model.OwnerID)
                @Html.HiddenFor(model => model.InstrumentPhoto)

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.InstrumentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InstrumentName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentTypeID, "Instrument Type", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("InstrumentTypeID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.InstrumentTypeID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="instrumentPhoto" />
                        @Html.ValidationMessageFor(model => model.InstrumentPhoto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
            </div>
        }
    }
    else if (User.IsInRole("Employee") && Model.OwnerID == User.Identity.GetUserId())
    {
        using (Html.BeginForm("Edit", "OwnerInstruments", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "bg-dark text-white p-2 rounded-3" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Instrument</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.OwnerInstrumentID)
                @Html.HiddenFor(model => model.DateAdded)
                @Html.HiddenFor(model => model.OwnerID)
                @Html.HiddenFor(model => model.InstrumentPhoto)

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.InstrumentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InstrumentName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentTypeID, "Instrument Type", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("InstrumentTypeID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.InstrumentTypeID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InstrumentPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="instrumentPhoto" />
                        @Html.ValidationMessageFor(model => model.InstrumentPhoto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            <div class="text-white">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
            </div>
        }
    }

    else
    {
        using (Html.BeginForm("Edit", "OwnerInstruments", FormMethod.Post, new { @class = "bg-dark text-white p-2 rounded-3" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Instrument</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.OwnerInstrumentID)
                @Html.HiddenFor(model => model.DateAdded)
                @Html.HiddenFor(model => model.OwnerID)
                @Html.HiddenFor(model => model.InstrumentName)
                @Html.HiddenFor(model => model.InstrumentTypeID)
                @Html.HiddenFor(model => model.IsActive)
                @Html.HiddenFor(model => model.InstrumentPhoto)

                <div class="form-group">
                    @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>

            <div class="text-white">
                @Html.ActionLink("Back to List", "Index", null, new { @class = "text-white" })
            </div>
        }
    }


</div>